server:
  port: ${PORT:9090}

spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/rideq}
    username: ${SPRING_DATASOURCE_USERNAME:rideq_user}
    password: ${SPRING_DATASOURCE_PASSWORD:StrongPassword123!}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true