spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update   # or validate in production
    show-sql: false

server:
  port: ${PORT:8080}

  spring:
    profiles:
      active: ${SPRING_PROFILES_ACTIVE:default}